"""
Modal deployment for State Research Tracker.

Builds from GitHub main branch.
Deploy with: modal deploy modal_app.py
"""

import datetime
import modal

app = modal.App("state-research-tracker")
RUNTIME_SECRET_NAME = "state-research-tracker-runtime"

REPO_URL = "https://github.com/PolicyEngine/state-legislative-tracker.git"
BRANCH = "main"

# Bump this when source code changes to rebuild the app layer
APP_VERSION = "v32"

# Evaluated at deploy time — unique command string busts Modal's layer cache
_now = datetime.datetime.utcnow().isoformat()

SUPABASE_ANON_KEY = (
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZm"
    "Z25ncWxnZnN2cWFydGlsZnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MjQ4OTgsImV4c"
    "CI6MjA4NDAwMDg5OH0.FprGrDgkfT0j3nK51VGtCozs6y1pfhtZ07qDUHBm8Go"
)

# Image: two layers so prerender always runs fresh while app build stays cached
image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install("curl", "ca-certificates", "git")
    .run_commands(
        # Install Node.js 20
        "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
        "apt-get install -y nodejs",
    )
    .run_commands(
        # Layer 1: Clone, install, build — cached until APP_VERSION is bumped
        f"echo 'app-build: {APP_VERSION}'",
        f"git clone --branch {BRANCH} --single-branch {REPO_URL} /app",
        "cd /app && npm install --legacy-peer-deps",
        # Anon key is public (read-only, row-level security enforced)
        "cd /app && VITE_SUPABASE_URL=https://ffgngqlgfsvqartilful.supabase.co"
        f" VITE_SUPABASE_ANON_KEY={SUPABASE_ANON_KEY}"
        " VITE_POSTHOG_KEY=phc_jrd8DSkxBiB4qr7mxqzizIFh0sIIZ0mSNSNGepllyGx"
        " npm run build",
    )
    .run_commands(
        # Layer 2: Pre-render — cache-busted every deploy to pick up new bills
        f"echo 'prerender: {_now}'",
        f"cd /app && SUPABASE_ANON_KEY={SUPABASE_ANON_KEY}"
        " node scripts/prerender.mjs",
    )
    .pip_install("fastapi", "uvicorn", "aiofiles", "httpx", "resend")
)


@app.function(
    image=image,
    allow_concurrent_inputs=100,
    secrets=[modal.Secret.from_name(RUNTIME_SECRET_NAME)],
)
@modal.asgi_app(label="state-legislative-tracker")
def web():
    """Serve static files with FastAPI."""
    from fastapi import FastAPI, HTTPException, Request
    from fastapi.staticfiles import StaticFiles
    from fastapi.responses import FileResponse, Response
    from pydantic import BaseModel
    import httpx
    import json
    import os

    api = FastAPI()
    http_client = httpx.AsyncClient()

    dist_path = "/app/dist"

    # Load valid routes generated by prerender script
    _routes_file = f"{dist_path}/_valid_routes.json"
    valid_routes = set(json.load(open(_routes_file))) if os.path.isfile(_routes_file) else set()

    # Serve static assets (renamed from assets/ to _tracker/ to avoid collisions with proxy host)
    if os.path.exists(f"{dist_path}/_tracker"):
        api.mount("/_tracker", StaticFiles(directory=f"{dist_path}/_tracker"), name="tracker_assets")

    # PostHog reverse proxy — routes analytics through our domain to avoid ad blockers
    POSTHOG_HOST = "https://us.i.posthog.com"
    POSTHOG_ASSETS_HOST = "https://us-assets.i.posthog.com"

    class BillAnalysisRequest(BaseModel):
        state: str
        bill_number: str
        title: str
        bill_url: str
        requester_email: str
        subscribe_newsletter: bool = False
        request_source: str | None = None

    async def store_request(payload: BillAnalysisRequest, request: Request):
        supabase_url = os.environ.get("SUPABASE_URL")
        supabase_key = os.environ.get("SUPABASE_KEY")
        if not supabase_url or not supabase_key:
            return False

        row = {
            "state": payload.state,
            "bill_number": payload.bill_number,
            "title": payload.title,
            "bill_url": payload.bill_url,
            "requester_email": payload.requester_email,
            "subscribe_newsletter": payload.subscribe_newsletter,
            "request_source": payload.request_source,
            "origin": str(request.base_url).rstrip("/"),
            "user_agent": request.headers.get("user-agent"),
        }

        response = await http_client.post(
            f"{supabase_url}/rest/v1/bill_analysis_requests",
            headers={
                "apikey": supabase_key,
                "Authorization": f"Bearer {supabase_key}",
                "Content-Type": "application/json",
                "Prefer": "return=representation",
            },
            json=row,
        )
        response.raise_for_status()
        return True

    def send_notification_email(payload: BillAnalysisRequest):
        import resend

        api_key = os.environ.get("RESEND_API_KEY")
        if not api_key:
            return False

        resend.api_key = api_key
        smtp_to = os.environ.get(
            "BILL_REQUEST_NOTIFICATION_TO",
            "hello@policyengine.org,pavel@policyengine.org",
        )
        recipients = [email.strip() for email in smtp_to.split(",") if email.strip()]

        resend.Emails.send({
            "from": "PolicyEngine Team <hello@policyengine.org>",
            "to": recipients,
            "subject": f"Score bill request: {payload.state} {payload.bill_number}",
            "html": (
                f"<p>A new bill analysis request was submitted.</p>"
                f"<p><strong>Requester:</strong> {payload.requester_email}</p>"
                f"<p><strong>Newsletter opt-in:</strong> {'yes' if payload.subscribe_newsletter else 'no'}</p>"
                f"<p><strong>Source:</strong> {payload.request_source or 'unknown'}</p>"
                f"<p><strong>Bill:</strong> {payload.state} {payload.bill_number}</p>"
                f"<p><strong>Title:</strong> {payload.title}</p>"
                f"<p><strong>Link:</strong> <a href='{payload.bill_url}'>{payload.bill_url}</a></p>"
            ),
        })
        return True

    @api.api_route("/ingest/{path:path}", methods=["GET", "POST", "OPTIONS"])
    async def posthog_proxy(path: str, request: Request):
        # Static assets come from a different host
        if path.startswith("static/"):
            target = f"{POSTHOG_ASSETS_HOST}/{path}"
        else:
            target = f"{POSTHOG_HOST}/{path}"

        headers = {
            k: v for k, v in request.headers.items()
            if k.lower() not in ("host", "content-length")
        }
        body = await request.body()

        resp = await http_client.request(
            method=request.method,
            url=target,
            headers=headers,
            content=body,
            params=dict(request.query_params),
        )
        # httpx decompresses gzip/br automatically, so strip hop-by-hop
        # and encoding headers to avoid browser trying to double-decompress
        excluded = {"content-encoding", "content-length", "transfer-encoding", "connection"}
        resp_headers = {
            k: v for k, v in resp.headers.items()
            if k.lower() not in excluded
        }
        return Response(
            content=resp.content,
            status_code=resp.status_code,
            headers=resp_headers,
        )

    @api.post("/api/bill-analysis-request")
    async def bill_analysis_request(payload: BillAnalysisRequest, request: Request):
        if "@" not in payload.requester_email or "." not in payload.requester_email.split("@")[-1]:
            raise HTTPException(status_code=400, detail="Please enter a valid email address.")

        result = {
            "stored": False,
            "notification_sent": False,
        }

        try:
            result["stored"] = await store_request(payload, request)
        except Exception as exc:
            raise HTTPException(status_code=500, detail=f"Could not store request: {exc}") from exc

        try:
            result["notification_sent"] = send_notification_email(payload)
        except Exception:
            result["notification_sent"] = False

        return result

    @api.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        """Serve the SPA with proper 404s for invalid routes."""
        file_path = f"{dist_path}/{full_path}"

        # If it's a file that exists, serve it
        if os.path.isfile(file_path):
            return FileResponse(file_path)

        # Check for pre-rendered directory page (e.g. /GA or /GA/ga-sb168)
        index_path = f"{file_path}/index.html"
        if os.path.isfile(index_path):
            return FileResponse(index_path)

        # Root path — serve homepage
        if not full_path:
            return FileResponse(f"{dist_path}/index.html")

        # Check if route is valid (known state or state/bill-id)
        # Normalize: strip trailing slash, uppercase first segment for state match
        normalized = full_path.strip("/")
        parts = normalized.split("/")
        route_key = parts[0].upper() if len(parts) == 1 else f"{parts[0].upper()}/{parts[1]}"

        if route_key in valid_routes:
            return FileResponse(f"{dist_path}/index.html")

        # Invalid route — return 404
        return Response(status_code=404, content="Not Found")

    return api
